default: &default
  adapter: mysql2
  pool: 5
  username: root
  password: 123.com
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: homework_controller

test:
  <<: *default
  database: homework_controller

production:
  <<: *default
  database: homework_controller
